---
dependencies: []

galaxy_info:
  role_name: second
  author: badsectorlabs
  description: Checks for a file /first.txt - for use in CI testing
  company: Bad Sector Labs
  license: GPLv3
  min_ansible_version: "2.10"
  platforms:
    - name: Windows
      versions:
        - "2012R2"
        - "2016"
        - "2019"
        - "2022"
    - name: Debian
      versions:
        - buster
        - bullseye
        - bookworm
    - name: Ubuntu
      versions:
        - bionic
        - focal
        - jammy

collections: []
